# Generated by Django 4.0.3 on 2022-04-10 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_student_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Option',
        ),
        migrations.CreateModel(
            name='AskedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_txt_1', models.CharField(blank=True, max_length=255, null=True)),
                ('option_txt_2', models.CharField(blank=True, max_length=255, null=True)),
                ('option_txt_3', models.CharField(blank=True, max_length=255, null=True)),
                ('option_txt_4', models.CharField(blank=True, max_length=255, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='asked_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.askedquestion'),
        ),
    ]
