# Generated by Django 4.0.3 on 2022-04-10 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_question_student_remove_student_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='asked_question',
        ),
        migrations.AddField(
            model_name='askedquestion',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.student'),
        ),
    ]
