# Generated by Django 4.0.3 on 2022-03-25 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_result_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='QuizQuestion',
        ),
    ]
