# Generated by Django 4.0.3 on 2022-03-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'Super_Sdmin'), ('student', 'Student')], default='super_admin', max_length=100),
        ),
    ]
