# Generated by Django 4.0.3 on 2022-03-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='readable_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
